CREATE DATABASE IF NOT EXISTS `lime-data`;
USE `lime-data`;

CREATE TABLE IF NOT EXISTS `cognitive-load` (
    id BIGINT NOT NULL AUTO_INCREMENT,
    student_id VARCHAR(50) NOT NULL,
    lesson_id VARCHAR(50) NOT NULL,
    session_id VARCHAR(100) DEFAULT NULL,
    minute_index INT NOT NULL,
    window_start DATETIME DEFAULT NULL,
    window_end DATETIME DEFAULT NULL,
    pause_frequency INT NOT NULL,
    navigation_count_video INT NOT NULL,
    rewatch_segments INT NOT NULL,
    playback_rate_change INT NOT NULL,
    idle_duration_video INT NOT NULL,
    time_on_content INT NOT NULL,
    navigation_count_adaptation INT NOT NULL,
    revisit_frequency INT NOT NULL,
    idle_duration_adaptation INT NOT NULL,
    quiz_response_time INT NOT NULL,
    error_rate FLOAT NOT NULL,
    predicted_cognitive_load VARCHAR(20) NOT NULL,
    predicted_score INT NOT NULL,
    confidence FLOAT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    INDEX idx_cognitive_load_student_lesson (student_id, lesson_id),
    INDEX idx_cognitive_load_session_minute (session_id, minute_index)
);

CREATE TABLE IF NOT EXISTS `student-lesson-summary` (
    id BIGINT NOT NULL AUTO_INCREMENT,
    student_id VARCHAR(50) NOT NULL,
    lesson_id VARCHAR(50) NOT NULL,
    session_id VARCHAR(100) DEFAULT NULL,
    minute_index INT NOT NULL DEFAULT 0,
    window_start DATETIME DEFAULT NULL,
    window_end DATETIME DEFAULT NULL,
    pause_frequency FLOAT NOT NULL,
    navigation_count_video FLOAT NOT NULL,
    rewatch_segments FLOAT NOT NULL,
    playback_rate_change FLOAT NOT NULL,
    idle_duration_video FLOAT NOT NULL,
    time_on_content FLOAT NOT NULL,
    navigation_count_adaptation FLOAT NOT NULL,
    revisit_frequency FLOAT NOT NULL,
    idle_duration_adaptation FLOAT NOT NULL,
    quiz_response_time FLOAT NOT NULL,
    error_rate FLOAT NOT NULL,
    predicted_cognitive_load VARCHAR(20) NOT NULL,
    predicted_score INT NOT NULL,
    confidence FLOAT NOT NULL,
    record_count INT NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_student_lesson (student_id, lesson_id),
    INDEX idx_summary_student_lesson (student_id, lesson_id)
);

CREATE TABLE IF NOT EXISTS `student-lesson-top-signals` (
    id BIGINT NOT NULL AUTO_INCREMENT,
    student_id VARCHAR(50) NOT NULL,
    lesson_id VARCHAR(50) NOT NULL,
    prediction_id BIGINT NOT NULL,
    predicted_cognitive_load VARCHAR(20) NOT NULL,
    predicted_score INT DEFAULT NULL,
    confidence FLOAT DEFAULT NULL,
    top_1_signal VARCHAR(255) DEFAULT NULL,
    top_1_value FLOAT DEFAULT NULL,
    top_1_normalized_value FLOAT DEFAULT NULL,
    top_2_signal VARCHAR(255) DEFAULT NULL,
    top_2_value FLOAT DEFAULT NULL,
    top_2_normalized_value FLOAT DEFAULT NULL,
    top_3_signal VARCHAR(255) DEFAULT NULL,
    top_3_value FLOAT DEFAULT NULL,
    top_3_normalized_value FLOAT DEFAULT NULL,
    lime_explanation JSON DEFAULT NULL,
    shap_explanation JSON DEFAULT NULL,
    human_explanation TEXT DEFAULT NULL,
    explanation_source VARCHAR(30) DEFAULT NULL,
    study_technique JSON DEFAULT NULL,
    lecture_support JSON DEFAULT NULL,
    shared_to_student BOOLEAN NOT NULL DEFAULT FALSE,
    shared_at DATETIME DEFAULT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_top_signals_student_lesson (student_id, lesson_id),
    INDEX idx_top_signals_prediction (prediction_id)
);
